fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305153_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305154_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305155_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305156_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305157_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305158_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305159_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305160_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305161_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305162_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305163_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305164_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305165_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305166_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305167_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305168_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305169_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305170_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305171_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305172_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305173_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305174_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305175_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305176_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305177_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305178_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305179_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305180_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305181_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305182_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305183_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305184_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305185_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305186_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305187_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305188_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305189_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305190_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305191_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305192_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305193_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305194_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305195_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305196_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305197_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305198_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305199_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305200_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305201_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305202_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305203_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305204_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305205_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305206_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305207_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305208_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305209_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305210_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305211_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305212_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305213_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305214_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305215_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305216_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305217_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305218_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305219_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305220_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305221_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305222_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305223_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305224_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305225_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305226_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305227_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305228_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305229_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305230_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305231_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305232_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305233_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305234_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305235_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305236_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305237_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305238_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305239_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305240_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305241_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305242_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305243_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305244_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305245_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305246_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305247_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305248_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305249_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305250_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305251_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305252_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305253_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305254_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305255_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305256_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305257_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305258_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305259_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305260_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305261_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305262_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305263_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305264_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305265_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305266_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305267_1.fastq
fastqc --outdir /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/QC/ /home/jgonzalezgom/01_NMELERO/RIBAS_CCELL_RNASEQ/fastq/SRR12305268_1.fastq
